const problems = [
	{
		name: 'Two Sum',
		link: 'https://leetcode.com/problems/two-sum/',
		topic: 'Array',
		solution: 'https://www.youtube.com/watch?v%NP9nLwKzXGA',
		level: 'Easy',
	},
	{
		name: 'Best Time to Buy and Sell Stock',
		link: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/',
		topic: 'Array',
		solution: 'https://www.youtube.com/watch?v%CCQBvgPages',
		level: 'Easy',
	},
	{
		name: 'Contains Duplicate',
		link: 'https://leetcode.com/problems/contains-duplicate/',
		topic: 'Array',
		solution: 'https://www.youtube.com/watch?v%XECOM0RnIig',
		level: 'Easy',
	},
	{
		name: 'Verifying an Alien Dictionary',
		link: 'https://leetcode.com/problems/verifying-an-alien-dictionary/',
		topic: 'Array',
		solution: 'https://www.youtube.com/watch?v%8NoyVvm1v88',
		level: 'Easy',
	},
	{
		name: 'Climbing Stairs',
		link: 'https://leetcode.com/problems/climbing-stairs/',
		topic: 'Dynamic Programming',
		solution: 'https://www.youtube.com/watch?v%N9syEXfu1Rw',
		level: 'Easy',
	},
	{
		name: "Pascal's Triangle",
		link: 'https://leetcode.com/problems/pascals-triangle/',
		topic: 'Dynamic Programming',
		solution: 'https://www.youtube.com/watch?v%f0EEHwaY3HY',
		level: 'Easy',
	},
	{
		name: 'Reverse a Linked List',
		link: 'https://leetcode.com/problems/reverse-a-linked-list/',
		topic: 'Linked List',
		solution: 'https://www.youtube.com/watch?v%FHhItaCZ2pE',
		level: 'Easy',
	},
	{
		name: 'Detect Cycle in a Linked List',
		link: 'https://leetcode.com/problems/linked-list-cycle/',
		topic: 'Linked List',
		solution: 'https://www.youtube.com/watch?v%k-gTqlOBT1g',
		level: 'Easy',
	},
	{
		name: 'Merge Two Sorted Lists',
		link: 'https://leetcode.com/problems/merge-two-sorted-lists/',
		topic: 'Linked List',
		solution: 'https://www.youtube.com/watch?v%Bwymxn-n6XA',
		level: 'Easy',
	},
	{
		name: 'Middle of the Linked List',
		link: 'https://leetcode.com/problems/middle-of-the-linked-list/',
		topic: 'Linked List',
		solution: 'https://www.youtube.com/watch?v%s7cHxJBuhjg',
		level: 'Easy',
	},
	{
		name: 'Valid Anagram',
		link: 'https://leetcode.com/problems/valid-anagram/',
		topic: 'String',
		solution: 'https://www.youtube.com/watch?v%qyQni3rz-ko',
		level: 'Easy',
	},
	{
		name: 'Valid Parentheses',
		link: 'https://leetcode.com/problems/valid-parentheses/',
		topic: 'String',
		solution: 'https://www.youtube.com/watch?v%D4l9TK0tWcI',
		level: 'Easy',
	},
	{
		name: 'Valid Palindrome',
		link: 'https://leetcode.com/problems/valid-palindrome/',
		topic: 'String',
		solution: 'https://www.youtube.com/watch?v%MFPmKyThyHk',
		level: 'Easy',
	},
	{
		name: 'Maximum Depth of Binary Tree',
		link: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/',
		topic: 'Tree',
		solution: 'https://www.youtube.com/watch?v%yi7ym5R5aYI',
		level: 'Easy',
	},
	{
		name: 'Subtree of Another Tree',
		link: 'https://leetcode.com/problems/subtree-of-another-tree/',
		topic: 'Tree',
		solution: 'https://www.youtube.com/watch?v%YOW_-ptARNE',
		level: 'Easy',
	},
	{
		name: 'High Five',
		link: 'https://leetcode.com/problems/high-five/',
		topic: 'Heap',
		solution: 'https://www.youtube.com/watch?v%z4c5QzarJxI',
		level: 'Easy',
	},
	{
		name: 'Number of 1 Bits',
		link: 'https://leetcode.com/problems/number-of-1-bits/',
		topic: 'Binary-Bit Manipulation',
		solution: 'https://www.youtube.com/watch?v%xx9vN3n0_SA',
		level: 'Easy',
	},
	{
		name: 'Counting Bits',
		link: 'https://leetcode.com/problems/counting-bits/',
		topic: 'Binary-Bit Manipulation',
		solution: 'https://www.youtube.com/watch?v%f9vCuICgRpU',
		level: 'Easy',
	},
	{
		name: 'Missing Number',
		link: 'https://leetcode.com/problems/missing-number/',
		topic: 'Binary-Bit Manipulation',
		solution: 'https://www.youtube.com/watch?v%-pLW7935dlc',
		level: 'Easy',
	},
	{
		name: 'Reverse Bits',
		link: 'https://leetcode.com/problems/reverse-bits/',
		topic: 'Binary-Bit Manipulation',
		solution: 'https://www.youtube.com/watch?v%-7bpRBMPXh8',
		level: 'Easy',
	},
];
